grails-app/domain/tenis/drive/HorarioLaboral.groovy
package tenis.drive

import valueObjects.RangoHorario

import java.time.DayOfWeek
import java.time.LocalDate

class HorarioLaboral {
    DayOfWeek dia;
    RangoHorario rangoHorario;

    static embedded = ['rangoHorario']

    HorarioLaboral(DayOfWeek dia, RangoHorario rangoHorario) {
        this.dia = dia;
        this.rangoHorario = rangoHorario;
    }

    Boolean abiertoEn(LocalDate fecha, RangoHorario rangoHorario) {
        return this.dia == fecha.dayOfWeek && this.rangoHorario.contiene(rangoHorario)
    }
}

grails-app/controllers/tenis/drive/HorarioLaboralController.groovy
package tenis.drive

import grails.validation.ValidationException
import valueObjects.RangoHorario

import java.time.DayOfWeek
import java.time.LocalTime
import java.time.format.DateTimeFormatter
import java.time.format.TextStyle

import static java.util.Locale.forLanguageTag
import static org.springframework.http.HttpStatus.*

class HorarioLaboralController {

    HorarioLaboralService horarioLaboralService
    ClubService clubService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond horarioLaboralService.list(params), model:[horarioLaboralCount: horarioLaboralService.count()]
    }

    def show(Long id) {
        HorarioLaboral horarioLaboral = horarioLaboralService.get(id);
        String diaSemana = horarioLaboral.getDia().getDisplayName(TextStyle.FULL, new Locale("ES"));
        diaSemana = diaSemana.substring(0, 1).toUpperCase() + diaSemana.substring(1);
        [dia: diaSemana, rangoHorario: horarioLaboral.getRangoHorario()]
    }

    def create() {
        //respond new HorarioLaboral(params)
        [horarioLaboral: new HorarioLaboral(params), club_id: params["club.id"]]
    }

    def save(HorarioLaboral horarioLaboral) {
        if (horarioLaboral == null) {
            notFound()
            return
        }

        try {
            horarioLaboralService.save(horarioLaboral)
        } catch (ValidationException e) {
            respond horarioLaboral.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'horarioLaboral.label', default: 'HorarioLaboral'), horarioLaboral.id])
                redirect horarioLaboral
            }
            '*' { respond horarioLaboral, [status: CREATED] }
        }
    }

    def guardar() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE", forLanguageTag("es"));
        DayOfWeek dia = DayOfWeek.from(formatter.parse(params.dia.toLowerCase()));
        RangoHorario rangoHorario = new RangoHorario(LocalTime.parse(params.horaInicio), LocalTime.parse(params.horaFin));

        HorarioLaboral horarioLaboral = new HorarioLaboral(dia, rangoHorario)

        try {
            horarioLaboralService.save(horarioLaboral)
        } catch (ValidationException e) {
            respond horarioLaboral.errors, view:'create'
            return
        }

        Club club = clubService.get(params.club_id)
        club.agregarHorarioLaboral(horarioLaboral)
        clubService.save(club)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'horarioLaboral.label', default: 'HorarioLaboral'), horarioLaboral.id])
                redirect horarioLaboral
            }
            '*' { respond horarioLaboral, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond horarioLaboralService.get(id)
    }

    def update(HorarioLaboral horarioLaboral) {
        if (horarioLaboral == null) {
            notFound()
            return
        }

        try {
            horarioLaboralService.save(horarioLaboral)
        } catch (ValidationException e) {
            respond horarioLaboral.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'horarioLaboral.label', default: 'HorarioLaboral'), horarioLaboral.id])
                redirect horarioLaboral
            }
            '*'{ respond horarioLaboral, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        horarioLaboralService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'horarioLaboral.label', default: 'HorarioLaboral'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'horarioLaboral.label', default: 'HorarioLaboral'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/horarioLaboral/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'horarioLaboral.label', default: 'HorarioLaboral')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-horarioLaboral" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-horarioLaboral" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.horarioLaboral}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.horarioLaboral}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.horarioLaboral}" method="POST" action="guardar">
                <fieldset class="form">
                    <p>Dia de la semana</p>
                    <g:select name="dia" from="['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo']" required="true" />
                    <p>Apertura</p>
                    <g:field name="horaInicio" type="time" required="true"/>
                    <p>Cierre</p>
                    <g:field name="horaFin" type="time" required="true"/>
                    <g:hiddenField name="club_id" value="${club_id}"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="guardar" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/horarioLaboral/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'horarioLaboral.label', default: 'HorarioLaboral')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-horarioLaboral" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-horarioLaboral" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.horarioLaboral}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.horarioLaboral}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.horarioLaboral}" method="PUT">
                <g:hiddenField name="version" value="${this.horarioLaboral?.version}" />
                <fieldset class="form">
                    <f:all bean="horarioLaboral"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/horarioLaboral/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'horarioLaboral.label', default: 'HorarioLaboral')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-horarioLaboral" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-horarioLaboral" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${horarioLaboralList}" />

            <div class="pagination">
                <g:paginate total="${horarioLaboralCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/horarioLaboral/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'horarioLaboral.label', default: 'HorarioLaboral')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-horarioLaboral" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-horarioLaboral" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <fieldset class="form">
                <p>Dia</p>
                <g:field name="diaDeSemana" readonly="true" value="${dia}" />
                <p>Rango Horario</p>
                <g:field name="rangoHorario" readonly="true" value="${rangoHorario}" />
            </fieldset>
            <g:form resource="${this.horarioLaboral}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.horarioLaboral}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>