grails-app/domain/tenis/drive/Cancha.groovy
package tenis.drive


import valueObjects.Turno

import java.time.LocalDate

class Cancha {
    String numero;
    List<Reserva> reservas;

    static constraints = {
    }

    Cancha(String numero) {
        this.numero = numero;
        this.reservas = []
    }

    Reserva reservar(Cliente cliente, Turno turno, BigDecimal horasConLuz, ITipoReserva tipoReserva) {
        List<Reserva> reservasEnFecha = reservas.stream().filter({ reserva -> reserva.coincideEnDiaDeSemana(turno.obtenerDia()) && reserva.estaActiva() }).collect();

        Boolean reservado = reservasEnFecha.any({ reservaEnFecha -> reservaEnFecha.enHorario(turno) })

        if (reservado) {
            throw new Exception("Ya existe una reserva en esa fecha y horario")
        }

        Reserva reserva = new Reserva(cliente, turno, horasConLuz, tipoReserva)
        reservas << reserva;
        return reserva;
    }

    /**
     * cambia la ocurrencia ó todas las ocurrencias de la reserva por un nuevo turno
     * @param reserva
     * @param nuevoTurno
     * @return (nuevaReserva, penalizacion)
     */
    def modificarReserva(Reserva reserva, Turno nuevoTurno, BigDecimal horasConLuz) {
        reserva.cancelar();
        BigDecimal costoPenalizacion = reserva.calcularPenalizacion();
        try {
            Reserva nuevaReserva = reservar(reserva.getCliente(), nuevoTurno, horasConLuz, reserva.getTipoReserva())
            return [nuevaReserva, costoPenalizacion];
        } catch (Exception e) {
            reserva.reActivar()
            throw e
        }
    }

    /**
     * Retorna una nueva reserva en el nuevo turno, con una penalizacion de 50% si se quiere dar de baja en el mismo dia.
     * @param reserva
     * @param fechaACambiar
     * @param turnoNuevo
     * @param horasConLuz
     * @return (nuevaReserva, penalizacion)
     */
    def modificarReservaUnicaFecha(Reserva reserva, LocalDate fechaACambiar, Turno turnoNuevo, BigDecimal horasConLuz) {
        reserva.cancelarUnicaFecha(fechaACambiar);
        BigDecimal costoPenalizacion = reserva.calcularPenalizacion(fechaACambiar);
        try {
            Reserva nuevaReserva = reservar(reserva.getCliente(), turnoNuevo, horasConLuz, new ReservaEsporadica())
            return [nuevaReserva, costoPenalizacion];
        } catch (Exception e) {
            reserva.reActivarEnFecha(fechaACambiar)
            throw e
        }
    }

}

grails-app/controllers/tenis/drive/CanchaController.groovy
package tenis.drive

import grails.validation.ValidationException
import valueObjects.RangoHorario
import valueObjects.Turno

import java.time.LocalDate
import java.time.LocalTime

import static org.springframework.http.HttpStatus.*

class CanchaController {

    CanchaService canchaService
    ClubService clubService
    ClienteService clienteService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond canchaService.list(params), model:[canchaCount: canchaService.count()]
    }

    def reservas(Long id) {
        Cancha cancha = canchaService.get(id)
        [cancha: cancha, reservas: cancha.reservas]
    }

    def show(Long id) {
        respond canchaService.get(id)
    }

    def create() {
        [cancha: new Cancha(params), club_id: params["club.id"]]
    }

    def save(Cancha cancha) {
        if (cancha == null) {
            notFound()
            return
        }

        try {
            canchaService.save(cancha)
        } catch (ValidationException e) {
            respond cancha.errors, view:'create'
            return
        }

        Club club = clubService.get(params.club_id)
        club.agregarCancha(cancha)
        clubService.save(club)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'cancha.label', default: 'Cancha'), cancha.id])
                redirect cancha
            }
            '*' { respond cancha, [status: CREATED] }
        }
    }


    def edit(Long id) {
        respond canchaService.get(id)
    }

    def update(Cancha cancha) {
        if (cancha == null) {
            notFound()
            return
        }

        try {
            canchaService.save(cancha)
        } catch (ValidationException e) {
            respond cancha.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'cancha.label', default: 'Cancha'), cancha.id])
                redirect cancha
            }
            '*'{ respond cancha, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        canchaService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'cancha.label', default: 'Cancha'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'cancha.label', default: 'Cancha'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    def reservar() {

        Reserva reserva = null;

        try {
            LocalDate fecha = LocalDate.parse(params.fecha)
            LocalTime horaInicio = LocalTime.parse(params.horaInicio)
            LocalTime horaFin = LocalTime.parse(params.horaFin)

            reserva = canchaService.reservar(params.id, params.cliente, fecha, horaInicio, horaFin, new BigDecimal(params.horasConLuz), params.tipoReserva)
        } catch (Exception e) {
            flash.error = e.message
            flash.params = params
            redirect(controller: "reserva", action: "create", id:params.id)
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'reserva.label', default: 'Reserva'), reserva.id])
                redirect action: "reservas", method: "GET", id: params.id
            }
            '*' { respond reserva, [status: CREATED] }
        }
    }


}

grails-app/views/cancha/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'cancha.label', default: 'Cancha')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-cancha" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-cancha" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.cancha}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.cancha}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.cancha}" method="POST">
                <fieldset class="form">
                    <f:all bean="cancha"/>
                    <g:hiddenField name="club_id" value="${club_id}"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/cancha/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'cancha.label', default: 'Cancha')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-cancha" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-cancha" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.cancha}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.cancha}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.cancha}" method="PUT">
                <g:hiddenField name="version" value="${this.cancha?.version}" />
                <fieldset class="form">
                    <f:all bean="cancha"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/cancha/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'cancha.label', default: 'Cancha')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-cancha" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-cancha" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:if test="${flash.warning}">
                <div class="message" role="status">${flash.warning}</div>
            </g:if>
            <table>
                <thead>
                    <tr>
                        <th>Numero</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <g:each var="cancha" in="${canchaList}">
                        <tr>
                            <td>
                                <a class="home" href="${createLink(uri: "/cancha/show/$cancha.id")}">
                                    ${cancha.numero}
                                </a>
                            </td>
                            <td>
                                <a class="home" href="${createLink(uri: "/cancha/$cancha.id/reserva/crear")}">
                                    Reservar
                                </a>
                                <br>
                                <a class="home" href="${createLink(uri: "/cancha/$cancha.id/reservas")}">
                                    Consultar reservas
                                </a>
                            </td>
                        </tr>
                    </g:each>
                </tbody>
            </table>

            <div class="pagination">
                <g:paginate total="${canchaCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/cancha/reservas.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'cancha.label', default: 'Cancha')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
            </ul>
        </div>
        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>
        <table>
            <thead>
            <tr>
                <th>Tipo</th>
                <th>Cliente</th>
                <th>Turno</th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
            </thead>
            <tbody>
            <g:each var="reserva" in="${reservas}">
                <tr>
                    <td>${reserva.tipoReserva}</td>
                    <td>${reserva.cliente}</td>
                    <td>${reserva.turno}</td>
                    <td>${reserva.estado}</td>
                    <td>
                        <a class="home" href="${createLink(uri: "/reserva/show/$reserva.id")}">
                            Detalles
                        </a>
                        <br/>
                        <a class="home" href="${createLink(uri: "/reserva/edit/$reserva.id")}">
                            Modificar
                        </a>
                        <br/>
                        <g:if test="${reserva.tipoReserva.instanceOf(tenis.drive.ReservaFija)}">
                            <a class="home" href="${createLink(uri: "/reserva/edit/$reserva.id/single")}">
                                Modificar unica fecha
                            </a>
                        </g:if>
                    </td>
                </tr>
            </g:each>
            </tbody>
        </table>
    </body>
</html>

grails-app/views/cancha/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'cancha.label', default: 'Cancha')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-cancha" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-cancha" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="cancha" />
            <g:form resource="${this.cancha}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.cancha}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>